name: tests
on: [push, pull_request]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 10.16.3

      - name: Install dependencies
        uses: borales/actions-yarn@v2.1.0
        with:
          cmd: install

      - name: Yarn Lint
        uses: borales/actions-yarn@v2.1.0
        with:
          cmd: lint
    
      - name: Yarn test
        uses: borales/actions-yarn@v2.1.0
        with:
          cmd: test
  coverage:
    needs: [ tests ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: "10.16.3"
      - run: npm install -g yarn
      - run: yarn install
      - run: yarn test
      - uses: paambaati/codeclimate-action@master
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageLocations:  ${{github.workspace}}/coverage/lcov.info:lcov
