name: tests
on: [push, pull_request]
jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 10.16.3
    
      - name: Yarn Lint
        uses: borales/actions-yarn@v2.1.0
        with:
          cmd: lint
    
      - name: Yarn test
        uses: borales/actions-yarn@v2.1.0
        with:
          cmd: test
    
      - name: Code Climate
        uses: paambaati/codeclimate-action@v2.2.4
